[theme]
base="light"
primaryColor="#667eea"
backgroundColor="#f8f9fa"
secondaryBackgroundColor="#e9ecef"
textColor="#2c3e50"
font="sans serif"

[theme.sidebar]
backgroundColor="#f1f3f4"
secondaryBackgroundColor="#e8eaed"